### ISSUE TITLE
EMail delivery on Google App Engine not working

### ISSUE THREAD

**Issue by maxgraser** [stefanw/seriesly#10]
Hi.

Since 1.April 2016 the EMail delivery function seem to be broken.

I already checked spamfilters, etc. but the last Email I received was on 31. March 2016. Other users of my site also reported not receiving EMails anymore since beginning of April.

Show-fetching and update of the calendar still seems to work. Also there are no errors or changes in the Logs. The Episode Guide seems to be up to date, too.

The mail-task is running without errors and I could not find any changes compared to last week.

I also could not find any changes regarding Google App engine, etc that would influence the Email delivery.

I already deployed the code once again (without any changes) but I have not observed any changes.

Can anybody help me in figuring out what has happened?
Is there another way to check if mails are being sent, except via Google App Engine Logging?

**Comment by stefanw** [comment]
[This is likely related to this issue](https://code.google.com/p/googleappengine/issues/detail?id=12786), also see comments in [this thread](https://news.ycombinator.com/item?id=11500981). Closing as unrelated to Seriesly itself.
