### ISSUE TITLE
Update to new Python/Django

### ISSUE THREAD

**Issue by moschlar** [stefanw/seriesly#2]
Hi @stefanw,

GAE keeps nagging to migrate to Python 2.7 which would require also updating from Django 1.1 to at least 1.2.

I might give that a try in the coming semester break, so I'd like to ask if you have any advice for that, since I'm not really into the Django world!

Cheers,
Moritz

**Comment by stefanw** [comment]
I started a refactor to Django 1.8 removing GAE dependencies completely. It's a WIP taking place #8. Closing this.
