### ISSUE TITLE
TVrage.com is down (for good?); Switch to alternate services is needed

### ISSUE THREAD

**Issue by maxgraser** [stefanw/seriesly#7]
TVrage.com is down since the beginning of [September](http://www.tvmaze.com/blogs/6/an-update-on-the-tvrage-situation), therefore we need to switch seriesly to another service which provides the needed data.

2 sites that seem to be here to stay are [TVDB](http://thetvdb.com/wiki/index.php?title=Programmers_API) and [TVmaze](http://www.tvmaze.com/api).

For a **quick fix** TVDB seems to be the solution, because its API uses xml syntax just like TVrage used to.

As a **second step** a switch to the TVmaze API (based on json) seems to provide some futureproofing. There already is a [python interface](https://github.com/srob650/pytvmaze) available to simplyfy implementation.

I will try to do the necessary changes on my own and provide the patch if I get it fixed.

_A few hints where to start and what to watch out for would be very welcome though. Have only some python experience involving HPC/ engineering code. Never worked on something involving the web..._

**Comment by stefanw** [comment]
Thanks for the update!

I'm totally willing to get away from the TVRage XML format (it was not so nice). Especially helpful that their API endpoint allows query by tvrage id!

I started a refactor of Seriesly with Django 1.8 and removing all GAE dependencies, it's happening in #8.

**Comment by maxgraser** [comment]
Because there are only a few users on my site, I didn't want to bother with writing a migration routine. But if I read your commit [#8](https://github.com/stefanw/seriesly/pull/8) correctly, you are already implementing such a routine?

**Comment by stefanw** [comment]
I will include an import of existing users (requiring a CSV export or similar from GAE first).

**Comment by maxgraser** [comment]
Great to know, thx!

**Comment by maxgraser** [comment]
Took me some time to get the hang of git and the timezone stuff, but the modfication seems complete. I uploaded it yesterday to my personal appspot incstance and will keep it running there to catch any bugs before putting together a pull request for you during weekend. Might even get the hang of rebase and clean up my commit history a bit.

We might need to work a little on the exceptions, because I removed some that are not relevant anymore. Didn't add new ones because I have next to zero knowhow of do's & dont's.

**Comment by moschlar** [comment]
If you have something ready, I'd be happy to testrun it to!

**Comment by maxgraser** [comment]
If you want to test it, checkout my branch:
https://github.com/maxgraser/seriesly/tree/TVMaze-Integration

For information how to use the submodule, i added some lines to the README.

**Comment by maxgraser** [comment]
Appart from online series not being imported all worked fine during the past "testing" week. I fixed the bug concerning online series like "House of Cards" (Netflix) and created a pull request.

Tried to simplify my commit history using rebase, but might have garbled it up somehow. : /
Files and commitlogs are fine though.

**Comment by maxgraser** [comment]
I'm seeing that you are updating the source code and incorporated pytvmaze.
Is serielsy working again, or "work in progress"?

I'm sorry if my contribution was not of much help...

**Comment by stefanw** [comment]
Yeah, TVMaze is now one working provider, thanks for pointing me to it.

I removed all App Engine dependencies and upgraded Django. The style is currently WIP, but it's working(tm). I'm running an instance on Heroku with some features disabled and a limited set of shows.
